# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
   encoders:
      Symfony\Component\Security\Core\User\User:
         algorithm: bcrypt
         cost: 13

   providers:
        in_memory:
            memory:
               users:
                  admin:
                     password: ""
                     roles: [ 'ROLE_ADMIN' ]

   firewalls:
         admin_secured_area:
            pattern: ^/admin/
            http_basic:
               realm: "Secured Admin Area"

   access_control:
      - { path: ^/admin/, roles: ROLE_ADMIN }
